### ISSUE TITLE
Loading icon keeps spinning.

### ISSUE THREAD

**Issue by jklmnn** [phiresky/nmap-log-parse#1]
When I load the page, the stats on the bottom are there, but the loading icon keeps spinning and it's not displaying the graphs. Firebug shows me the following error: `TypeError: self is undefined` on line 145 in program.js.
I'm using Firefox 40.0.3 on Linux Mint.
My config.js:

``` json
{
  "input": "logs/nmap.log",
  "macToName": {},
  "hostToName": {},
  "logInterval": 6,
  "ignoreLessThan": 1,
  "self": "shuttle"
}
```

**Comment by phiresky** [comment]
Looks like that happens if no entries are found with the self hostname (`shuttle` in your case)

I added a workaround that calculates percentages based on the device that is online the most instead. But try looking at the stats output, your raspberry hostname is probably shown as something else.

**Comment by jklmnn** [comment]
That fixed it. Thanks :)
