### ISSUE TITLE
Charts aren't shown

### ISSUE THREAD

**Issue by Mrtenz** [phiresky/nmap-log-parse#3]
I installed it on my Raspberry Pi and it kinda works. I can see the connected devices in the table, but the charts keep blank. Developer console says `Warning: Could not find any entries with self hostname (undefined), calculations will be less accurate` I didn't change anything in the config.js except for the log path.

**Comment by phiresky** [comment]
Please pull again / redownload. That warning should not appear anymore.

For the missing charts, how long have you had it running? It aggregates the data over an hour, so you will only start seeing anything after >1h after adding the cron script

**Comment by Mrtenz** [comment]
After a pull the charts show up and the warning is gone.
