### ISSUE TITLE
Not seeing nmap results

### ISSUE THREAD

**Issue by frasertheking** [phiresky/nmap-log-parse#8]
Perhaps I'm not entering the command correctly, but I did:

sudo EDITOR=nano crontab -e

and entered:
`*/10 * * * * nmap -sn 192.168.2.* -oX - >> /home/monitor/logs`

And i'm not seeing anything being generated in /home/monitor/logs? Am I doing something wrong? Thanks!

**Comment by phiresky** [comment]
That looks right.

Did you wait more than 10 minutes?

If you run the editor again, is the line still there?

**Comment by frasertheking** [comment]
Yeah! I've waited an hour or so and nothing has shown up in /home/monitor/logs which confuses me

**Comment by phiresky** [comment]
If you run the editor again, is the line still there?

**Comment by frasertheking** [comment]
Sorry, yeah I still see it there

**Comment by phiresky** [comment]
Which distro/version are you using? Is cron running? If it is search for the cron logs.. e.g. `journalctl -u cron` or `/var/log/syslog` depending on the system

**Comment by frasertheking** [comment]
I'm running the latest version of raspbian on my pi. I ran journalctl -u cron and got "No journal files were found". I haven't done anything with cron before, perhaps it isn't running? Thanks for your assistance

**Comment by phiresky** [comment]
Seems like Raspbian should have cron running by default, but with [logs disabled](http://raspberrypi.stackexchange.com/questions/3741/where-do-cron-error-message-go). Does the file /home/monitor/logs not exist or is it empty? What happens if you run `sudo nmap -sn "192.168.2.*" -oX -`? Also try putting quotes around the address.

**Comment by frasertheking** [comment]
Right now /home/monitor/logs is just an empty directory I made for this. I ran that command and got a response with the devices on my network so it looks like that command worked

**Comment by frasertheking** [comment]
is logs supposed to be a file? Maybe thats where I got confused

**Comment by phiresky** [comment]
Yes, the redirection has to be into a file (which does not have to exist)

**Comment by frasertheking** [comment]
Ohhh okay! What type of file is logs? a text file? Or how do I make it?

**Comment by phiresky** [comment]
It's a normal plain text file. You don't have to create it manually, but it can't already exist and be a folder ;)

**Comment by frasertheking** [comment]
Okay! I deleted my logs folder and now I'll wait 10 minutes! Thanks for the help again!

**Comment by phiresky** [comment]
Sure! I'll close this assuming it will work, otherwise leave another comment.
