### ISSUE TITLE
How to view the data in the index.html file

### ISSUE THREAD

**Issue by frasertheking** [phiresky/nmap-log-parse#9]
Hey!

So my log file has been gathering data for about a week now, but when I open the index.html file on my pi the boxes are all blank (I don't get any errors at the top either). How am I supposed to open the file to actually see the graphs etc.?

Thanks again for your help

**Comment by phiresky** [comment]
Go to the console (F12), are there any errors? Are you opening index.html via `file:///` or via a server?

The path to the logs file in the .json has to be relative to index.html and accessible to the server.

**Comment by frasertheking** [comment]
I think I figured it out actually! Thanks!
